WIP coverage.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,10 +20,10 @@ jobs:
         schema:
           - env: latest
             image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:latest-dev"
-          - env: release
-            image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:25.07.01"
-          - env: next-release
-            image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:26.02.17-RC01"
+          # - env: release
+          #   image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:25.07.01"
+          # - env: next-release
+          #   image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:26.02.17-RC01"
           # - env: previous
           #   image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:25.07.01"
     name: build and test (jdk ${{matrix.jdk}}, schema ${{matrix.schema.env}})
@@ -56,6 +56,25 @@ jobs:
           label: 'Build'
           status: ${{ job.status == 'success' && 'Pass' || 'Fail' }}
           file: ${{ matrix.jdk }}/${{ matrix.schema.env }}.svg
+          run_id: ${{ github.run_id }}
+      - name: Install xmllint
+        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
+      - name: coverage
+        id: coverage
+        run: |
+          ./gradlew codeCoverageReport --info --init-script init.gradle -PCDA.oracle.database.image=${{matrix.schema.image}}
+          MISSED_LINES=`xmllint --xpath "string(/report/counter[@type='COMPLEXITY']/@missed)" cwms-data-api/build/reports/jacoco-composite.xml`
+          COVERED_LIENS=`xmllint --xpath "string(/report/counter[@type='COMPLEXITY']/@covered)" cwms-data-api/build/reports/jacoco-composite.xml`
+          PERCENT=`printf "%.0f %%" $(( (COVERED_LINES /(COVERED_LIENS + MISSED_LINES)) * 100 ))`
+          echo "Coverage from missed $MISSED_LINES and covered $COVERED_LINES is $PRECENT"
+          echo "coverage=$PERCENT" >> $GITHUB_OUTPUT
+      - name: Create matrix coverage badge
+        if: success() || failure() # always run even if the previous step fails
+        uses: ./.github/actions/badge
+        with:
+          label: 'Coverage'
+          status: ${{ steps.coverage.outputs.coverage }}
+          file: ${{ matrix.jdk }}/${{ matrix.schema.env }}-coverage.svg
           run_id: ${{ github.run_id }}
       # - name: Publish Test Report
       #   uses: mikepenz/action-junit-report@v5
