Create friendly test report
https://github.com/HydrologicEngineeringCenter/cwms-database use this and it's much nicer than digging through the action output.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,13 @@ jobs:
         run: ./gradlew build --info --init-script init.gradle
       - name: integration tests
         run: ./gradlew integrationtest --info --init-script init.gradle
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          annotate_only: true
+          include_passed: true
+          report_paths: '**/test*.xml'
   build-docker-image:
     runs-on: ubuntu-latest
     steps:
