Create badge set so we can see individual what is and isn't ready at a glance.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,6 +14,9 @@ jobs:
       fail-fast: false
       matrix:
         jdk: [11]
+        # place holder for now and leaving commented but in place. General scheme target tests again the current release, the next release, the previous release, and latest development.
+        # at this time every possible instance of concern is on 25.07.01, once 26.02.17 is finalized it becomes release and 25.07.01 becomes previous.
+        # next-release will be comment out until such time as a RC gets made
         schema:
           - env: latest
             image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:latest-dev"
@@ -21,11 +24,8 @@ jobs:
             image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:25.07.01"
           - env: next-release
             image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:26.02.17-RC01"
-# place holder for now and leaving commented but in place. General scheme target tests again the current release, the next release, the previous release, and latest development.
-# at this time every possible instance of concern is on 25.07.01, once 26.02.17 is finalized it becomes release and 25.07.01 becomes previous.
-# next-release will be comment out until such time as a RC gets made
-#          - env: previous
-#           image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:25.07.01"
+          # - env: previous
+          #   image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:25.07.01"
     name: build and test (jdk ${{matrix.jdk}}, schema ${{matrix.schema.env}})
     runs-on: ubuntu-latest
     outputs:
@@ -49,25 +49,21 @@ jobs:
         run: ./gradlew clean build --info --init-script init.gradle
       - name: integration tests
         run: ./gradlew integrationtest --info --init-script init.gradle -PCDA.oracle.database.image=${{matrix.schema.image}}
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v5
+      - name: Create matrix job badge
         if: success() || failure() # always run even if the previous step fails
-        with:
-          annotate_only: true
-          include_passed: true
-          report_paths: '**/TEST-*.xml'
-      - name: Build Badge
-        uses: emibcn/badge-action@v2.0.2
+        uses: ./.github/actions/badge
         with:
           label: 'Build'
-          status: 'Ok'
-          color: 'blue,555,daf'
-          path: 'badges/${{ matrix.jdk }}/${{ matrix.schema.env }}.svg'
-      - name: Upload badge
-        uses: actions/upload-artifact@v4
-        with:
-          name: badges_${{ github.run_id }}_${{ matrix.jdk}}_${{ matrix.schema.env }}
-          path: badges/**/*.svg
+          status: ${{ job.status == 'success' && 'Pass' || 'Fail' }}
+          file: ${{ matrix.jdk }}/${{ matrix.schema.env }}.svg
+          run_id: ${{ github.run_id }}
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@v5
+      #   if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     annotate_only: true
+      #     include_passed: true
+      #     report_paths: '**/TEST-*.xml'
   open-api-static-analysis:
     name: OpenApi Static Analysis Tests
     runs-on: ubuntu-latest
@@ -105,6 +101,7 @@ jobs:
     steps:
       - name: checkout code
         uses: actions/checkout@v5.0.0
+      # No uploads, we're just verifying that nothing broke the docker image.
       - name: Build Migration image
         uses: ./.github/actions/database-migration-image
         with:
@@ -112,29 +109,31 @@ jobs:
           # TODO get current target image from build information
           tag: latest-dev
 
-      # No uploads, we're just verifying that nothing broke the docker image.
+
+
   badges:
     needs: build
     runs-on: ubuntu-latest
+    # we are reporing build state so always run
+    if: always()
     steps:
       - name: Badge Branch
         uses: actions/checkout@v5.0.0
         with:
           ref: badges
           fetch-depth: 1
-          path: badge-workingdir
       - name: Download badges
         uses: actions/download-artifact@v4
         with:
           pattern: badges_${{ github.run_id }}_*
-          path: ./ # directory to download artifacts into
+          path: ./build  # directory to download artifacts into
           merge-multiple: true  # downloaded artifacts will be in the same directory specified by path
       - name: Apply Badge
-        working-directory: badge-workingdir
         run: |
-          mkdir build
+          find . -type f
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
-          git add build/${{ matrix.jdk }}/${{ matrix.schema.env }}.svg
-          git commit -m "Update Badge for build ${{ github.event.ref }}"
-          git push origin badges
+          git add build/**/*.svg
+          git status
+          git commit --allow-empty -m "Update Badge for build ${{ github.event.ref }}"
+          git push origin badges -f
